version: "3"

services:
  mysql:
    container_name: mysql-container
    image: mysql:8
    restart: on-failure
    volumes:
      - ./data:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env

  api:
    container_name: api-container
    build: .
    image: animes-review-api
    restart: on-failure
    command: [
      "./wait-for-it.sh",
      "mysql-container:$DB_PORT",
      "--timeout=300",
      "--",
      "npm",
      "run",
      "start:prod"
    ]
    volumes:
      - ./dist:/usr/app/animes-review-api/dist
      - ./public:/usr/app/animes-review-api/public
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-container
      WAIT_HOSTS: mysql-container:${DB_PORT}
    env_file:
      - .env
