version: "3"

services:
  mysql:
    container_name: mysql-container
    image: mysql:8
    restart: on-failure
    volumes:
      - ./data/db:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env

  redis:
    container_name: redis-container
    image: redis
    restart: on-failure
    volumes:
      - ./data/redis:/data/redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env

  api:
    container_name: api-container
    build: .
    image: animes-review-api
    restart: on-failure
    command: [
      "./wait-for-it.sh",
      "mysql-container:$DB_PORT",
      "--timeout=300",
      "--",
      "pm2-runtime",
      "dist/src/main.js",
    ]
    volumes:
      - ./dist:/usr/app/animes-review-api/dist
      - ./public:/usr/app/animes-review-api/public
    ports:
      - "${PORT}:${PORT}"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql-container
      REDIS_HOST: redis-container
    env_file:
      - .env
